'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''

def fibonacci_even_sum(num1, num2, fib_sum):
    if num1 + num2 < 4000000 :
        new_num  = num1 + num2
        if new_num % 2 == 0:
            fib_sum += new_num
        return fibonacci_even_sum(num2, new_num, fib_sum)
    else:
        return fib_sum




if __name__ == '__main__':
    print fibonacci_even_sum(1,1, 0)
